### ISSUE TITLE
Apparently not working with Java 13

### ISSUE THREAD

**Issue by meltemi-ml** [ebean-orm/ebean-eclipse-enhancer#12]
The enhancer cannot process any file, showing **Unsupported class file major version 57** errors instead. Java version: 13.

### Error log

```
java.lang.IllegalArgumentException: Unsupported class file major version 57
	at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:184)
	at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:166)
	at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:152)
	at io.ebean.eclipse.internal.enhancer.builder.EnhanceBuilder$DetermineClass.getClassName(EnhanceBuilder.java:194)
	at io.ebean.eclipse.internal.enhancer.builder.EnhanceBuilder.process(EnhanceBuilder.java:118)
	at io.ebean.eclipse.internal.enhancer.builder.EnhanceBuilder.checkResource(EnhanceBuilder.java:96)
	at io.ebean.eclipse.internal.enhancer.builder.EnhanceBuilder.access$0(EnhanceBuilder.java:92)
	at io.ebean.eclipse.internal.enhancer.builder.EnhanceBuilder$DeltaVisitor.visit(EnhanceBuilder.java:255)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:67)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:51)
	at io.ebean.eclipse.internal.enhancer.builder.EnhanceBuilder.build(EnhanceBuilder.java:53)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

### Session data

```
eclipse.buildId=4.14.0.I20191210-0610
java.version=13.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product
```

**Comment by rbygrave** [comment]
The alternative to using the plugin for eclipse is to register the javaagent to the JRE Runtime.

If you look at: https://ebean.io/docs/getting-started/ ... and then click on the "Eclipse IDE" tab, that shows screen shots of registering the javaagent with the JRE. Then run the project using that JRE (and turn off the plugin).

Do you want to try that?

**Comment by meltemi-ml** [comment]
Thanks for looking into it. I followed the guide, after a quick check the agent seems to work properly
